server:
  port: ${PORT:8084}

app:
  mail:
    from: ${APP_MAIL_FROM:gadgetmart.77777@gmail.com}

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  mail:
    host: smtp.gmail.com
    port: 587
    username: gadgetmart.77777@gmail.com
    password: ${GMAIL_APP_PASSWORD:dilh qufc vnbm ykui}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
