server:
  port: ${PORT:8761}

eureka:
  client:
    register-with-eureka: false # Do not register itself
    fetch-registry: false       # Do not fetch registry from itself
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  server:
    wait-time-in-ms-when-sync-empty: 0
