server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # Do not register itself
    fetch-registry: false       # Do not fetch registry from itself
  server:
    wait-time-in-ms-when-sync-empty: 0
